# Generated by Django 5.1.7 on 2025-03-14 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
